### ISSUE TITLE
Manully adding ids

### ISSUE THREAD

**Issue by siresnow** [WeeabooGod/Greenluma-Reborn-Manager#3]
Manully adding ids, the app doesnt reconize youve added them
![image](https://user-images.githubusercontent.com/20748228/103434192-19dfd880-4bbb-11eb-80a1-dd127c87f97c.png)

![image](https://user-images.githubusercontent.com/20748228/103434199-28c68b00-4bbb-11eb-928f-1e5e64ab77a7.png)

**Comment by WeeabooGod** [comment]
Been such a while, sorry for not keeping this program up to date. I don't think I ever programmed manually adding functionality. Usually, if its not on the Steam.DB then it doesn't exist, or I never had to manually add to begin with.

My program uses a profile.json file to deal with profiles. It reffers to that json file to generate the AppList.  If you need to manually add AppID's you would need to manually add them within the JSON file. Since Manually editing doesn't refresh the program you would then need to close/relaunch the program after editing, or just switch profiles, edit, then load profile.

Its been months, so I am mostly writing this for others who might come across this program and wish to use it. Unsure why, I am a trash programmer. I did this for myself mostly as I often got tired of the python one often failing for me.
